### ISSUE TITLE
Simpler Experience

### ISSUE THREAD

**Issue by Tolmark12** [abe33/atom-figlet#1]
Would be cool if there was a hook to simply convert the selected text into ASCII text without picking the font every time.

**Comment by gnclmorais** [comment]
I agree with this.  
Also, my keybinding is not working… Is it just me?

**Comment by abe33** [comment]
Sorry for the late reply, I completely forgot about this issue. I'll push a patch today.

@gnclmorais Which binding do you use?

**Comment by abe33** [comment]
@gnclmorais: The bindings issue should be fixed too, I forgot to update the selector when Atom dropped space-pen views.

**Comment by gnclmorais** [comment]
Yup, the keybinding is working now. :smile: Thanks!
