### ISSUE TITLE
Add / keep comment

### ISSUE THREAD

**Issue by m1ga** [abe33/atom-figlet#3]
Could you add an option that it keeps // in front of very line?
I want to convert a comment like
~~~
// test
~~~
so that each line will start with //

as a workaround
~~~
/* test */
~~~
and selecting just the test and turn it into a figlet is working. But most of my one line comments are with //

**Comment by abe33** [comment]
Hi, thanks for your suggestion, seems like an interesting feature, I don't know when I'll be able to implement it though, do you want to give it a shot by yourself?

**Comment by m1ga** [comment]
Tried it and it worked :)
https://github.com/abe33/atom-figlet/pull/4

Going to add some more options at the weekend (possibility to change the comment characters)

**Comment by m1ga** [comment]
Needs more features like this but its too complicated for me to implement:

>  * preserve comments that make sure to only convert the text after the comment and then prefix every lines of the ascii version with the comment.

>  * generate as comments that force the resulting ascii to be prefixed with the comments structure of the current language (#, //, etc.)

>  * use block comments that, when generate as commentsis enabled, will use the block comments form instead of the inline one, but only if the current language is actually supporting a block comment form.

maybe someone else can help

**Comment by abe33** [comment]
No problem, I'll take a look at that myself when I can get some time.

**Comment by abe33** [comment]
This is still a naive implementation as it doesn't handle block comments at this point. I need to figure the best way to handle them before supporting them.
