### ISSUE TITLE
Strip leading and trailing empty lines.

### ISSUE THREAD

**Issue by p0lm** [abe33/atom-figlet#6]
Some fonts, such as 'colossal' may have leading or trailing empty lines, if no 'high' (capitals and such) or 'long' ('j, p') etc are present in the text. 

It'd be a nice idea to provide a setting that automatically strips these.

**Comment by abe33** [comment]
Yes, I think it's a good idea too. I plan to take some time to work on this package in a near future so I include that on my TODO.

Thanks for the suggestion
